# Generated by Django 5.1.5 on 2025-11-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('response', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
